[[redirects]]
  from = "/search"
  to = "https://limonblogapi.herokuapp.com/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"